// Catalog data — Pav Klasa's public catalog
// Categories: WORK | ATOM | METHOD | TOOL | DEAD | WRITING | FEED

const ENTRIES = [
  // ========== WORK (case studies) ==========
  {
    id: "PVK-26-000", cat: "WORK", year: 2026, status: "live",
    title: "Scoraq — Bridge the gap between ideas and execution",
    short: "Founder & designer. A working operating system for product teams turning brief into ship.",
    tags: ["founder", "saas", "product", "0→1"],
    body: "Most product teams have plenty of ideas and plenty of tickets — and a chasm in between. Scoraq sits in that chasm. It's a workspace that holds a brief, an exploration, a decision, and the work that follows it as one continuous artefact rather than four disconnected ones. Built on the conviction that the document is the team, not the meeting. Designing it, founding it, shipping it.",
    metrics: [["Stage", "Live"], ["Role", "Founder · Design lead"], ["Domain", "scoraq.com"]],
    company: "Scoraq",
    role: "Founder",
    refs: ["scoraq.com/info"],
  },
  {
    id: "PVK-24-001", cat: "WORK", year: 2024, status: "shipped",
    title: "Hazelcast Management Center — Cluster Topology",
    short: "Real-time spatial view of a distributed in-memory data grid. 40k+ partitions, sub-second updates.",
    tags: ["enterprise", "data-viz", "react", "websocket"],
    body: "Replaced a tabular member list with a force-directed graph rendering the live partition table. The hard problem wasn't drawing nodes — it was deciding what to omit. At 40k partitions, density kills meaning. We collapsed by membership group, exposed only the migrating partitions in motion, and let users drill into a single member without leaving the canvas.",
    metrics: [["MAU", "12.4k"], ["Time-to-incident", "−68%"], ["Released", "v5.4"]],
    company: "Hazelcast",
    role: "Lead Product Designer",
    refs: ["hazelcast.com/products/management-center"],
  },
  {
    id: "PVK-24-002", cat: "WORK", year: 2024, status: "shipped",
    title: "SQL Browser for the In-Memory Engine",
    short: "Query a 200-node cluster like it's a single database. Notebook-style with cell history.",
    tags: ["sql", "developer-tools", "monaco"],
    body: "Engineers were leaving our product to run queries in third-party tools. We built a Monaco-backed query surface with first-class support for streaming results, plan visualisation, and the SQL dialects unique to a distributed engine. Notebooks save to the cluster itself, so a 3am incident query is still there next morning.",
    metrics: [["Adoption", "73% of clusters"], ["Avg session", "11min"]],
    company: "Hazelcast",
    role: "Lead Product Designer",
  },
  {
    id: "PVK-23-003", cat: "WORK", year: 2023, status: "shipped",
    title: "Viridian Cloud Console",
    short: "Self-serve cluster provisioning from zero to running query in under 90 seconds.",
    tags: ["cloud", "onboarding", "billing"],
    body: "The free-tier flow used to take 14 minutes and 9 screens. We compressed it to a single configuration sheet — region, size, name — and committed everything else to defaults. The defaults were the design.",
    metrics: [["TTFQ", "1m 24s"], ["Activation", "+41%"]],
    company: "Hazelcast",
    role: "Lead Product Designer",
  },
  {
    id: "PVK-22-004", cat: "WORK", year: 2022, status: "shipped",
    title: "Streaming Pipeline Builder",
    short: "Drag-to-compose Jet pipelines. Source → transform → sink, with live throughput on every edge.",
    tags: ["node-editor", "canvas", "streams"],
    body: "Most pipeline UIs lie about scale — pretty for the demo, useless past 30 nodes. We built a deterministic auto-layout, edge-bundling at high zoom-out, and a panel that shows backpressure as it happens. The canvas can hold a 400-node pipeline without flinching.",
    metrics: [["Max nodes tested", "412"], ["TTI", "240ms"]],
    company: "Hazelcast",
  },
  {
    id: "PVK-21-005", cat: "WORK", year: 2021, status: "archived",
    title: "Kibana Plugin — Cache Insights",
    short: "Side-by-side cache and index telemetry inside an existing observability stack.",
    tags: ["plugin", "elastic", "observability"],
    body: "Built when 'observability' meant five tools open at once. The plugin surfaced cache hit ratios next to query latencies in the Kibana the ops team already lived in. Deprecated when we shipped our own console — but the lesson, meet users where they are, is still the right one.",
    company: "Hazelcast",
  },

  // ========== ATOM (components & screens) ==========
  {
    id: "PVK-24-101", cat: "ATOM", year: 2024,
    title: "DataTable — virtualised, resizable, sticky everything",
    short: "10M-row table component with column pinning, group headers, and inline edit.",
    tags: ["react", "virtualisation", "table"],
    body: "Three years of incremental work distilled into one component. Row virtualisation via fixed-height windowing, column virtualisation by intersection observer, sticky group headers via position: sticky pyramids. Used across six products.",
    refs: ["github.com/pawelklasa (private)"],
  },
  {
    id: "PVK-24-102", cat: "ATOM", year: 2024,
    title: "CommandBar — universal launcher",
    short: "⌘K palette with action providers, fuzzy match, and recent-history weighting.",
    tags: ["react", "search", "kbd"],
    body: "Action providers are pluggable: any feature can register entries that surface in the bar. Fuzzy matcher uses sub-sequence + acronym scoring; recents get a logarithmic boost. The animation is intentionally fast — 80ms — because the bar should disappear before you finish thinking about it.",
  },
  {
    id: "PVK-23-103", cat: "ATOM", year: 2023,
    title: "InlineDiff — semantic JSON delta",
    short: "Side-by-side and unified diff, with structural awareness.",
    tags: ["json", "diff", "monaco"],
    body: "Stops yelling about whitespace. Renames are detected and shown as renames. Reordered arrays don't appear changed unless you ask for ordered comparison.",
  },
  {
    id: "PVK-23-104", cat: "ATOM", year: 2023,
    title: "Toast — deterministic, stack-aware",
    short: "No spinning queue. No 'dismiss all'. Replaces itself with newer state.",
    tags: ["react", "state"],
    body: "Toasts in most systems are a ledger. This one is a register: a new toast for the same key replaces the old one in place. Three slots maximum, oldest evicted. Less honest, more useful.",
  },
  {
    id: "PVK-22-105", cat: "ATOM", year: 2022,
    title: "Sparkline — 1px-anti-aliased",
    short: "Crisp inline metric chart at 16×40, no library.",
    tags: ["svg", "data-viz"],
    body: "Library sparklines blur because they don't respect device pixels. This one snaps to half-pixel grid, draws a polyline of integer Y, and looks correct at 1× and 2×. 1.4kb gzipped.",
  },

  // ========== METHOD (patterns & heuristics) ==========
  {
    id: "PVK-METHOD-01", cat: "METHOD", year: 2024,
    title: "The Empty State Test",
    short: "If your empty state is a shrug, your filled state is a lie.",
    tags: ["heuristic", "writing"],
    body: "Design the empty state first. Not the 'first-run welcome' empty state — the one a power user lands in when their cluster has zero alerts. If you can only describe it as 'No items', the feature is decoration. If you can give it a default action, a metric to brag about, a useful link — the feature has earned its panel.",
  },
  {
    id: "PVK-METHOD-02", cat: "METHOD", year: 2024,
    title: "Defaults Are The Design",
    short: "Every config knob is a confession that the team couldn't decide.",
    tags: ["heuristic", "decision"],
    body: "Knobs scale linearly in cost and quadratically in support burden. Ship with one opinion. If two equally-valid opinions exist, pick one and document the other as 'why we didn't'. The user can always file a feature request — they cannot un-confuse themselves at 2am.",
  },
  {
    id: "PVK-METHOD-03", cat: "METHOD", year: 2023,
    title: "The Hairline Rule",
    short: "If a line is only there to separate, it should be 1px and the lightest possible value.",
    tags: ["visual", "heuristic"],
    body: "Borders are not architecture. They are stitches. A thick border says 'this thing matters'; if everything matters, nothing does. Reserve thick lines for actual emphasis (a sidebar edge, a focused element). The rest gets a hairline at 8% opacity. Density without noise.",
  },
  {
    id: "PVK-METHOD-04", cat: "METHOD", year: 2023,
    title: "Tooltips Are An Apology",
    short: "Every tooltip is a label that didn't fit. Ask why it didn't fit.",
    tags: ["heuristic", "writing"],
    body: "Sometimes the answer is honest — a chart's data point can't carry text. But often the answer is that the icon was wrong, or the column header was wrong, or the action was hidden when it shouldn't have been. Audit your tooltips quarterly and earn back what you can.",
  },

  // ========== TOOL (downloadable) ==========
  {
    id: "PVK-TOOL-01", cat: "TOOL", year: 2024, status: "available",
    title: "Hairline Grid (Figma)",
    short: "12-col, 8pt-baseline working file. Includes the only auto-layout cheat sheet you'll need.",
    tags: ["figma", "grid", "starter"],
    body: "A working file, not a 'design system'. 12 columns, 8pt baseline, and three pre-built layouts I rebuild on every project anyway. Fork it.",
    download: "hairline-grid-v3.fig",
    size: "1.2 MB",
  },
  {
    id: "PVK-TOOL-02", cat: "TOOL", year: 2024, status: "available",
    title: "useStickyState — React hook",
    short: "useState that survives a page reload. 18 lines. No dependencies.",
    tags: ["react", "hook", "snippet"],
    body: "Drop-in replacement for useState that persists to localStorage with a serializer hook. Used in every prototype I make.",
    download: "useStickyState.ts",
    size: "612 bytes",
  },
  {
    id: "PVK-TOOL-03", cat: "TOOL", year: 2023, status: "available",
    title: "Interview Kit — Senior PD",
    short: "The take-home brief and rubric I used to hire 3 designers at Hazelcast.",
    tags: ["hiring", "rubric"],
    body: "A small brief that takes ~2 hours. The rubric scores process, craft, and communication on equal footing. Open-sourced because hiring rubrics shouldn't be a trade secret.",
    download: "interview-kit.pdf",
    size: "84 KB",
  },

  // ========== DEAD (failed experiments) ==========
  {
    id: "PVK-DEAD-01", cat: "DEAD", year: 2023, status: "shelved",
    title: "Voice-controlled query builder",
    short: "\"Show me caches with hit-ratio under 40 percent.\" Worked. Nobody used it.",
    tags: ["voice", "experiment"],
    body: "Built it for a hackathon, demo'd well, shipped to beta. Engineers don't talk to their tools — they like silence and they like their hands on the keyboard. Lesson: novel input modalities solve discovery problems they don't have.",
  },
  {
    id: "PVK-DEAD-02", cat: "DEAD", year: 2022, status: "shelved",
    title: "Skeuomorphic gauge dashboard",
    short: "Brushed steel, drop shadows, the works. Looked great at 1×; illegible at 2×.",
    tags: ["dashboard", "skeuo"],
    body: "Tried to make ops feel like a control room. Turns out ops engineers don't want to feel like anything — they want their numbers in a row, sortable. Killed after a week of usability sessions where the kindest feedback was 'it's nice'.",
  },

  // ========== WRITING (Medium articles) ==========
  {
    id: "PVK-WR-01", cat: "WRITING", year: 2026, when: "Apr 20, 2026", status: "published",
    title: "On being a designer in the most interesting, exhausting moment of our careers.",
    short: "The Four Pressures.",
    tags: ["essay", "bootcamp", "craft"],
    body: "Pinned essay for Bootcamp on the simultaneous compression of design's tooling, scope, audience, and pace. Argues that the 'four pressures' aren't separate forces — they're the same shift, observed from four sides, and that the only durable response is to commit harder to taste rather than retreat into process.",
    refs: ["medium.com/design-bootcamp/on-being-a-designer-in-the-most-interesting-exhausting-moment-of-our-careers-7284735e0927"],
  },
  {
    id: "PVK-WR-02", cat: "WRITING", year: 2025, when: "Sep 5, 2025", status: "published",
    title: "The AI Winter Is Coming",
    short: "Scale gave us a tool, not a mind.",
    tags: ["essay", "ai", "forecast"],
    body: "Pinned. Argues that the gap between capability demos and durable utility is wider than the funding cycle accounts for, and outlines what an actual winter looks like for design teams who've already restructured around the prediction.",
    refs: ["medium.com/@pawel.klasa/the-ai-winter-is-coming-096b4fcaa461"],
  },
  {
    id: "PVK-WR-03", cat: "WRITING", year: 2026, when: "Apr 27, 2026", status: "published",
    title: "The AI Winter Has Started.",
    short: "Seven months later…",
    tags: ["essay", "ai", "follow-up"],
    body: "The follow-up to the September forecast. A field report, not a victory lap.",
    refs: ["medium.com/design-bootcamp/the-ai-winter-has-started-7b3fa237077e"],
  },
  {
    id: "PVK-WR-04", cat: "WRITING", year: 2026, when: "Apr 22, 2026", status: "published",
    title: "Color is finally OK",
    short: "A solo developer's blog post replaced sixty years of color science. Most designers and developers missed it.",
    tags: ["color", "oklch", "craft"],
    body: "On the quiet arrival of OKLCH in browsers and what it changes about how we should specify color in design tokens — perceptually uniform contrast, predictable mixing, and the death of the eyedropper hex value.",
    refs: ["medium.com/design-bootcamp/color-is-finally-ok-82f368f3408c"],
  },
  {
    id: "PVK-WR-05", cat: "WRITING", year: 2026, when: "Apr 19, 2026", status: "published",
    title: "Figma Is Fine. Your Job Might Not Be.",
    short: "Claude Design launched 48 hours ago. Here is what it actually means.",
    tags: ["essay", "ai", "figma", "tooling"],
    body: "A working designer's first impressions of Claude Design and what it implies for the next eighteen months of the discipline. Less doom than headlines suggest; more rearrangement than panic.",
    refs: ["medium.com/design-bootcamp/figma-is-fine-your-job-might-not-be-df42ee0e33a4"],
  },
  {
    id: "PVK-WR-06", cat: "WRITING", year: 2025, when: "Feb 26, 2025", status: "published",
    title: "The \u201CWeekend Thief\u201D: Why Most Design Take-Homes are Broken",
    short: "On the unpaid labour we still call screening.",
    tags: ["hiring", "essay", "ethics"],
    body: "The take-home brief is the most defended bad idea in our hiring stack. Argues for a paid 90-minute pairing exercise instead, and provides a rubric (see PVK-TOOL-03).",
    refs: ["medium.com/design-bootcamp/the-weekend-thief-why-most-design-take-homes-are-broken-850465045404"],
  },
  {
    id: "PVK-WR-07", cat: "WRITING", year: 2025, when: "Nov 25, 2025", status: "published",
    title: "Hands-On review of building with Claude Opus 4.5",
    short: "The Agent on the Keyboard.",
    tags: ["ai", "review", "workflow"],
    body: "Two-week working diary. What it's good at (interface scaffolds, refactors, the boring 60%), what it isn't (taste, restraint, knowing when to stop), and what changed about my day-to-day as a result.",
    refs: ["medium.com/design-bootcamp/hands-on-review-of-building-with-claude-opus-4-5-e587fd877775"],
  },
  {
    id: "PVK-WR-08", cat: "WRITING", year: 2025, when: "Sep 19, 2025", status: "published",
    title: "Harry Beck's Radical Idea: A Lesson in Disruption",
    short: "The Tube Map: A Case Study in User-Centred Design.",
    tags: ["history", "information-design"],
    body: "How a draughtsman with no remit redrew London by ignoring its geography. The argument: the most useful thing you can do for a user is to stop showing them what's true and start showing them what's relevant.",
    refs: ["medium.com/design-bootcamp/harry-becks-radical-idea-a-lesson-in-disruption-6637fe2ac38e"],
  },
  {
    id: "PVK-WR-09", cat: "WRITING", year: 2025, when: "Sep 17, 2025", status: "published",
    title: "How Apple's New iOS Design Fails at Accessibility",
    short: "Losing Sight of Clarity.",
    tags: ["accessibility", "ios", "critique"],
    body: "A specific, measurable critique. Contrast ratios, hit targets, motion budgets — the things that used to be load-bearing in Apple's HIG and aren't, in places, anymore.",
    refs: ["medium.com/design-bootcamp/how-apples-new-ios-design-fails-at-accessibility-0c51151d645e"],
  },
  {
    id: "PVK-WR-10", cat: "WRITING", year: 2025, when: "Sep 15, 2025", status: "published",
    title: "We Fired Our Personas",
    short: "How archetypes turned our design chaos into a clear path forward.",
    tags: ["research", "personas", "archetypes"],
    body: "The smiley-face persona problem in B2B big-data tools, and why an archetype framework — fewer, sharper, role-based — gave the team a usable shorthand the personas never managed.",
    refs: ["medium.com/design-bootcamp/why-i-ditched-smiley-personas-for-an-archetype-framework-in-big-data-design-3518fe442923"],
  },
];

window.ENTRIES = ENTRIES;
